import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Heading } from "@/components/Heading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-full flex-col overflow-hidden`}
      >
        <Heading level={1} className="p-4">
          College Squash Map
          <span className="block text-sm font-normal md:hidden">
            (no map in mobile)
          </span>
        </Heading>
        <hr className="w-full border-t border-gray-600" />
        <div className="p-4 h-full">{children}</div>
      </body>
    </html>
  );
}
